Fail on any exit code if configured to fail
And don't fail regardless of exit code if not configured to fail. This
replaces the previous behavior of ignoring exit code and look for output
in the log to determine if weeds were found or not.

Before, a fatal error that produced no stdout, would not fail. This is
much better. The only gap it leaves is if we're configured _not_ to
fail, we probably still want fatal errors other than weeds-found to fail
the Job. We will resolve that next.

Fixes #13.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -43,11 +43,20 @@ runs:
 
         cd '${{ inputs.working-directory }}'
         prefix=$(echo '${{ inputs.working-directory }}' | sed 's|/$||')/
-        weeder ${{ inputs.weeder-arguments }} |
-          sed "s|^|$prefix|; "'s/$/ is not used by any defined root/' |
-          tee "$tmp" || true
 
-        if ${{ inputs.fail }} && [[ -s "$tmp" ]]; then
+        ret=0
+
+        if ! weeder ${{ inputs.weeder-arguments }} |
+          sed "s|^|$prefix|; "'s/$/ is not used by any defined root/' |
+          tee "$tmp"; then
+          ret=$?
+        fi
+
+        # If we succeed, we can always succed regardless of version
+        ((ret)) || exit 0
+
+        # If we're configured to fail, we can always fail regardless of version
+        if ${{ inputs.fail }}; then
           echo "Configured to fail and unused functions found"
-          exit 1
+          exit $ret
         fi
